import Head from 'next/head'
import Carousel from '../Components/Carousel'
import Counter from '../Components/HomeCounter'
import Link from 'next/link'
import moment from 'moment'
import TeamMembers from '../Components/TeamMembers'
import Footer from '../Components/Footer-2'

const {BLOG_URL, CONTENT_API_KEY} = process.env

type Post = {
  title: string
  slug: string
  updated_at: number
  html : string
}

async function getPosts() {
  const res = await fetch(`${BLOG_URL}/ghost/api/content/posts/?key=${CONTENT_API_KEY}&fields=title,html,slug,updated_at&limit=5`).then(res => res.json())

  console.log(res)
  const posts = res.posts

  return posts
}

export const getStaticProps = async ({ params }) => {
  const posts = await getPosts()
  return {
    revalidate: 30,
    props: { posts }
  }
}

const Home: React.FC<{ posts: Post[] }> = (props) => {

  const { posts } = props
  return (
    <div className='home-div'>
      <Head>
        <title>Aretecom LTD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-1.png" />
      </Head>
      <Carousel />
      <Counter />
      <div className='blog-div'>
        <h1 className='latest-h1 text-center'>Latest Articles</h1>
          {posts.map((post) => {
            return (
              <div className="post-div" key={post.slug}>
                <h1 className='post-title'>{post.title}</h1>
                <p className='post-date'>{moment(post.updated_at).format('MMMM Do YYYY, h:mm:ss a')}</p>
                <div dangerouslySetInnerHTML={{__html: post.html}} className="index_post_html"></div>
                <Link href="/post/[slug" as={`/post/${post.slug}`}><a className='read-more text-end'>Read More</a></Link>
              </div>
            )
          })}
      </div>
      <TeamMembers />
      <Footer />
    </div>
  )
}
export default Home